### ISSUE TITLE
Add Snapshots & State Sync section

### ISSUE THREAD

**Issue by SeanZoR** [lavanet/docs#106]
Snapshots are available from some node runners but it isn't written in our Docs.
Add it to both join-testnet's options (with/without Cosmovisor).

List of snapshots:
- https://polkachu.com/testnets/lava/snapshots
- https://beta.quicksync.io/networks/lava.html (temp UI, but snapshots work)

In the past we had a section already about snapshots but we removed it (https://github.com/lavanet/docs/pull/59)

**Comment by appieasahbie** [comment]
https://github.com/appieasahbie/Lava-Snapshots (Daily update and directly to use)

**Comment by SeanZoR** [comment]
I have added the state sync to the title now that it's supported in `lavad` 0.9.8

**Comment by KagemniKarimu** [comment]
🗄️ Archived this issue;  section with Testnet Services currently exists in the docs!
